import { ethers } from "ethers";
import * as fs from "fs";
import * as path from "path";

// ERC-8004 Identity Registry ABI (simplified)
const IDENTITY_ABI = [
  "function registerAgent(string _name, string _metadataURI, address _agentWallet) returns (uint256)",
  "function getAgentIdentity(uint256 _agentId) view returns (string name, address wallet, uint256 createdAt, uint256 reputation, bool isActive)",
  "function getReputation(uint256 _agentId) view returns (uint256)",
  "event AgentRegistered(uint256 indexed agentId, string name, address wallet)",
];

// Compiled contract bytecode (would be generated by solc in production)
// For now, we'll use a pre-compiled version or deploy manually

async function main() {
  console.log("🚀 Deploying ERC-8004 Agent Identity...\n");

  // Check for private key
  const privateKey = process.env.AGENT_WALLET_PRIVATE_KEY;
  const rpcUrl = process.env.RPC_URL || "https://sepolia.infura.io/v3/demo";

  if (!privateKey) {
    console.error("❌ Missing AGENT_WALLET_PRIVATE_KEY in .env");
    console.log("\n📝 Steps to deploy:");
    console.log("1. Create a wallet or use existing one");
    console.log("2. Get testnet ETH from faucet:");
    console.log("   - Sepolia: https://sepoliafaucet.com");
    console.log("   - Base Sepolia: https://www.base.org/faucet");
    console.log("3. Add private key to .env:");
    console.log("   AGENT_WALLET_PRIVATE_KEY=your_private_key");
    console.log("   RPC_URL=https://sepolia.infura.io/v3/YOUR_KEY");
    return;
  }

  // Connect to network
  const provider = new ethers.JsonRpcProvider(rpcUrl);
  const wallet = new ethers.Wallet(privateKey, provider);
  
  console.log("📍 Network:", rpcUrl.includes("sepolia") ? "Sepolia Testnet" : "Custom");
  console.log("👤 Deployer:", wallet.address);
  
  const balance = await provider.getBalance(wallet.address);
  console.log("💰 Balance:", ethers.formatEther(balance), "ETH");
  
  if (balance === 0n) {
    console.error("\n❌ Insufficient balance. Get testnet ETH from faucet.");
    return;
  }

  console.log("\n⏳ Deploying contract...");

  // For production, you'd deploy the compiled bytecode
  // Here we'll output the steps for manual deployment via Remix or similar
  
  console.log("\n📋 DEPLOYMENT OPTIONS:\n");
  console.log("Option 1: Deploy via Remix IDE");
  console.log("  1. Go to https://remix.ethereum.org");
  console.log("  2. Create new file: ERC8004Identity.sol");
  console.log("  3. Paste contract code from contracts/ERC8004Identity.sol");
  console.log("  4. Compile with Solidity 0.8.20");
  console.log("  5. Deploy to Sepolia/Base Sepolia");
  console.log("  6. Copy deployed address to .env\n");
  
  console.log("Option 2: Deploy via Foundry/Hardhat");
  console.log("  bunx hardhat run scripts/deploy-hardhat.ts --network sepolia\n");
  
  // Save deployment info
  const deploymentInfo = {
    network: rpcUrl.includes("sepolia") ? "sepolia" : "unknown",
    deployer: wallet.address,
    timestamp: new Date().toISOString(),
    instructions: "Deploy contract via Remix and add IDENTITY_REGISTRY_ADDRESS to .env",
  };
  
  fs.writeFileSync(
    path.join(__dirname, "deployment-info.json"),
    JSON.stringify(deploymentInfo, null, 2)
  );
  
  console.log("📄 Deployment info saved to scripts/deployment-info.json");
}

main().catch(console.error);
